module.exports = [
    "MBBS - Bachelor of Medicine, Bachelor of Surgery",
    "BDS - Bachelor of Dental Surgery",
    "BAMS - Bachelor of Ayurvedic Medicine and Surgery",
    "BUMS - Bachelor of Unani Medicine and Surgery",
    "BHMS - Bachelor of Homeopathy Medicine and Surgery",
    "Bachelor of Occupational Therapy",
    "Bachelor of Science in Biotechnology",
    "Bachelor of Technology in Biomedical Engineering",
    "Bachelor of Science in Microbiology (Non-Clinical)",
    "Doctor of Medicine (MD)",
    "Masters of Surgery (MS)",
    "Diplomate of National Board (DNB)",
    "Master of Surgery (MS)",
    "D.M.",
    "M.Ch",
    "Anaesthesiology",
    "Ear, Nose and Throat",
    "Biochemistry",
    "General Surgery",
    "Anatomy",
    "Community Health",
    "Ophthalmology",
    "Dermatology",
    "Orthopedics",
    "Family Medicine",
    "Obstetrics and Gynaecology",
    "Emergency Medicine",
    "Forensic Medicine",
    "Dermatology, Venerology and Leprosy",
    "General Medicine",
    "Field Epidemiology",
    "Microbiology",
    "Paediatrics",
    "Palliative Medicine",
    "Pathology",
    "Health Administration",
    "Pharmacology",
    "Immunohematology and transfusion medicine",
    "Physical Medicine and Rehabilitation",
    "Maternal and Child Health",
    "Physiology",
    "Preventive and Social Medicine",
    "Nuclear Medicine",
    "Psychiatry",
    "Obstetric and Gynecology",
    "Radio-Diagnosis",
    "Radio-Therapy",
    "Orthopedic Surgery",
    "Tuberculosis and Respiratory diseases",
    "Oto-Rhino Laryngology",
    "Emergency and Critical care",
    "Transfusion Medicine",
    "Skin and Vereral diseases",
    "Tropical Medicine",
    "Respiratory diseases",
    "Rural Surgery",
    "Social and Preventive Medicine",
    "Surgery",
    "Cardiac-Anaesthesiology",
    "Cardiothoracic and Vascular Surgery",
    "Cardiology",
    "Gastrointestinal Surgery",
    "Hematology",
    "Obstetrics and Gyaecology",
    "ENT",
    "Anaesthesiology, Pain Medicine and Critical Care",
    "Neuro Surgery",
    "Endocrinology",
    "Pediatric Surgery",
    "Gastroenterology",
    "Plastic and Reconstructive Surgery",
    "Medicine and Microbiology",
    "Surgical Oncology",
    "Pediatrics",
    "Surgery Trauma Centre",
    "Nephrology",
    "Urology",
    "Nureo-Anaesthesiology and Critical Care",
    "Nuerology",
    "Onco-Anesthesiology and Palliative Medicine",
    "Pulmonary and Sleep disorders",
    "Obstetrics and Gynecology",
    "Cardiac-Radiology",
]